### PR TITLE
Fixes delete buttons and other crashes

### LINKED ISSUE #104: Fix delete buttons on events
Clients also probably do not work.

### PR DESCRIPTION
**Pull request by awtpi314**
fixed everything to match the prisma schema
fixed rewards connecting to event
fixed crashes when modifying or deleting rewards

Closes #104

### CODE REVIEW

File: src/controllers/clientController.ts [hunk 1]
```diff
@@ -16,7 +16,7 @@ export const add: Express.RequestHandler = async (req, res) => {
     data: {
       alias,
       macAddress,
-      event,
+      eventId: event,
```
Comment (SpBills) [inline src/controllers/clientController.ts:19]: prefer

```ts
event: {
  id: event
}
```

**Review by SpBills — APPROVED** [review]
LGTM
